# Generated by Django 4.1.2 on 2022-10-15 12:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('message', ckeditor.fields.RichTextField()),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Authentication.repeatfields',),
        ),
    ]
