# Generated by Django 4.0.6 on 2022-10-15 11:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Categories',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.repeatfields')),
                ('category_name', models.CharField(max_length=150)),
            ],
            bases=('User.repeatfields',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.repeatfields')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Food_Images')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ingredients', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Action.food_categories')),
            ],
            bases=('User.repeatfields',),
        ),
    ]
