# Generated by Django 4.1.2 on 2022-10-15 14:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description_food',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
